/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bot;

import java.util.Random;

/**
 *
 * @author Oscar
 */
public class Chat extends javax.swing.JFrame {

    /**
     * Creates new form Cbhat
     */
    public Chat() {
        initComponents();
        this.setSize(660, 460);
        this.setLocationRelativeTo(null);
        directionMatrix(50);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        chatArea = new javax.swing.JTextArea();
        userMsj = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(241, 239, 239));
        jPanel4.setLayout(null);

        chatArea.setEditable(false);
        chatArea.setColumns(20);
        chatArea.setRows(5);
        jScrollPane1.setViewportView(chatArea);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(213, 30, 400, 320);

        userMsj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userMsjActionPerformed(evt);
            }
        });
        jPanel4.add(userMsj);
        userMsj.setBounds(210, 370, 360, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/send.gif"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel1);
        jLabel1.setBounds(580, 360, 40, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userMsjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userMsjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userMsjActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        chat = chatArea.getText();
   
        if(userMsj.getText().equals("")){
            System.out.println("Empty message!");
        }
        else{
            chatArea.setText(chat.concat(userMsj.getText() + "\n"));
            String response = talkToMe(userMsj.getText());
            userMsj.setText("");
            chat = chatArea.getText();
            
            //puntos y respuesta
            hiloPuntos = new Hilo(chatArea,response);
            pts = new Thread(hiloPuntos);
            pts.start();
            
        }
        
        
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private String talkToMe(String user){
        String response = "";
        user = user.toLowerCase();
        Random r = new Random();
        int num = r.nextInt(3) + 1;
        
        //Greetings
        if(user.equals("hi") || user.contains("hello") || user.contains("hola")){
            response = "Hello";
        }
        
        if(user.contains("my name is") || user.contains("i am") || user.contains("i'm")){
            if(user.contains("my name is")){
                userName = user.substring(10);
            }
            else if(user.contains("i am")){
                userName = user.substring(4);
            }
            else if(user.contains("i'm")){
                userName = user.substring(3);
            }
           
            response = "Nice to meet you" + userName;
        }
        
        if(user.contains("who") && user.contains("you")){
            response = "My name is Korra";
        }
        System.out.println(response);
        return response;
    }
    
    private int[][] directionMatrix(int n){
        int dir[][] = new int[n][n];
        for(int i = 0; i < n; i++){
            for(int j = 0; j < 50; j++){
                if(i >= j)
                    System.out.print("[ X ]");
                
                else
                    System.out.print("[ 1 ]");
            }
            
            System.out.println("");
        }
        return dir;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea chatArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField userMsj;
    // End of variables declaration//GEN-END:variables
    String chat= "";
    String userName = "";
    public Hilo hiloPuntos;
    Thread pts;
}


